### PR TITLE
finished lab 5

### PR DESCRIPTION
**Pull request by alexam2179**

### CODE REVIEW

**Comment by khatchad** [comment]
Nothing to grade here. Please advise.

**Comment by alexam2179** [comment]
What do you mean there is nothing to grade? I Commited my work and pushed
it  ?

**Comment by khatchad** [comment]
See https://github.com/cst1201-d644/Introducing-Methods/pull/7/files https://github.com/cst1201-d644/Introducing-Methods/pull/7/files.

**Comment by alexam2179** [comment]
Professor this was a month ago, it's Memorial day weekend, I'm not home
what am I supposed to do about it now? I know I did it and I submitted work
through Github. It has always been giving me problems and I told you about
it after the final that this hasn't been graded, I cannot see the problem
through my phone.

**Comment by khatchad** [comment]
Yes, I realize that this was a month ago and it is because that there was initially no pull request. I have been grading later assignments and I am now circling back to these. At this point in the semester, I have not been taking extra submissions. Unfortunately, there’s nothing to do here, unfortunately.

**Comment by alexam2179** [comment]
But I did pull request.  This is really not my fault I told you we had a
problem after the final, and we had a 0 from it when we really did the
work.

**Comment by khatchad** [comment]
Ah you're correct. There was a pull request. In fact, I commented on this a month ago (please see above):

> khatchad commented 23 days ago
> Nothing to grade here. Please advise.

**Comment by khatchad** [comment]
It looks like in https://github.com/alexam2179/Introducing-Methods/commit/1065a8b9511a2dd9f49141bbc760152e8582d00b you erased your file.

**Comment by khatchad** [comment]
I see that there is work in the previous commit (see https://github.com/alexam2179/Introducing-Methods/commit/dcf4ed6eda7cd3548b1668d2a4f12ca33d794a89). Is that what you wanted me to grade?

**Comment by khatchad** [comment]
And, yes, I do now recall that you mentioned something after the final but it would have been helpful to come to me sooner. Please let me know about https://github.com/alexam2179/Introducing-Methods/commit/dcf4ed6eda7cd3548b1668d2a4f12ca33d794a89.

**Comment by khatchad** [comment]
Please let me know by Tuesday (when grades are due).

**Comment by alexam2179** [comment]
Yes that is the one that I committed to be graded. Maybe I had problems
with it and committed it few times, thank you.

**Pull request closed without merging**
